// This file is automatically generated. Do not edit it directly.
import { supabase } from "./client";

// SPA-compatible auth check - no middleware needed
export async function requireSupabaseAuth() {
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error || !user) {
    throw new Error("Authentication required");
  }
  return { supabase, userId: user.id };
}
